<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Credit</name>
   <tag></tag>
   <elementGuidId>1ff421aa-5754-4804-88bf-d8552148d3b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='anchor0']/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0fb64dc3-7cf1-44c0-baee-97a9ee9ad700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-binding</value>
      <webElementGuid>28dea499-1ec8-48a6-892d-628d921e996e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Credit</value>
      <webElementGuid>fcb1f0b2-3f86-4f15-b3a7-1f90bfddbf68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;anchor0&quot;)/td[@class=&quot;ng-binding&quot;]</value>
      <webElementGuid>3b238538-a28b-4ebe-a9aa-1250b9651940</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='anchor0']/td[3]</value>
      <webElementGuid>5ec65fe5-5f01-46b7-b716-7c5a935d1655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sep 10, 2023 9:55:34 PM'])[1]/following::td[2]</value>
      <webElementGuid>2e36e5a9-1e37-4f89-bb01-35668bfebfd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Type'])[1]/following::td[3]</value>
      <webElementGuid>d0ccfa59-f550-4e5c-a864-e9f0e1ef1893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/preceding::td[1]</value>
      <webElementGuid>13a0fb2f-6b3d-4363-b68d-b373afbb52ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top'])[1]/preceding::td[1]</value>
      <webElementGuid>1de2d4d1-cb39-475d-b387-f122149efa5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Credit']/parent::*</value>
      <webElementGuid>1b5cbbbf-b11c-426d-850f-3a6066c6e9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td[3]</value>
      <webElementGuid>7ddcd72b-9066-4a5d-95e5-660096e8b678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Credit' or . = 'Credit')]</value>
      <webElementGuid>a580916e-8a46-40e8-aac9-56b55af8d820</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
